<h1>SETTING OPTIONS</h1>

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', 500) #SHOW UP TO 500 COLUMNS
pd.set_option('display.max_rows', 500) #SHOW UP TO 500 ROWS

In [43]:
#df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv") 
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")

#print(df)

# df.gr

In [3]:
df.head()

data stato  codice_regione denominazione_regione        lat  \
0  2020-02-24T18:00:00   ITA              13               Abruzzo  42.351222   
1  2020-02-24T18:00:00   ITA              17            Basilicata  40.639471   
2  2020-02-24T18:00:00   ITA              21          P.A. Bolzano  46.499335   
3  2020-02-24T18:00:00   ITA              18              Calabria  38.905976   
4  2020-02-24T18:00:00   ITA              15              Campania  40.839566   

        long  ricoverati_con_sintomi  terapia_intensiva  totale_ospedalizzati  \
0  13.398438                       0                  0                     0   
1  15.805148                       0                  0                     0   
2  11.356624                       0                  0                     0   
3  16.594402                       0                  0                     0   
4  14.250850                       0                  0                     0   

   isolamento_domiciliare  totale_positivi  variazione_totale_positivi  \
0                       0                0                           0   
1                       0                0                           0   
2                       0                0                           0   
3                       0                0                           0   
4                       0                0                           0   

   nuovi_positivi  dimessi_guariti  deceduti  totale_casi  tamponi  \
0               0                0         0            0        5   
1               0                0         0            0        0   
2               0                0         0            0        1   
3               0                0         0            0        1   
4               0                0         0            0       10   

   casi_testati note_it note_en  
0           NaN     NaN     NaN  
1           NaN     NaN     NaN  
2           NaN     NaN     NaN  
3           NaN     NaN     NaN  
4           NaN     NaN     NaN

In [4]:
df.tail()

data stato  codice_regione denominazione_regione  \
1801  2020-05-19T17:00:00   ITA               9               Toscana   
1802  2020-05-19T17:00:00   ITA              22           P.A. Trento   
1803  2020-05-19T17:00:00   ITA              10                Umbria   
1804  2020-05-19T17:00:00   ITA               2         Valle d'Aosta   
1805  2020-05-19T17:00:00   ITA               5                Veneto   

            lat       long  ricoverati_con_sintomi  terapia_intensiva  \
1801  43.769231  11.255889                     190                 56   
1802  46.068935  11.121231                      42                  8   
1803  43.106758  12.388247                      25                  2   
1804  45.737503   7.320149                      26                  1   
1805  45.434905  12.338452                     259                 18   

      totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
1801                   246                    2077             2323   
1802                    50                     154              204   
1803                    27                      39               66   
1804                    27                      22               49   
1805                   277                    3477             3754   

      variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
1801                        -250               7             6653       992   
1802                         -44               7             3699       455   
1803                         -11               3             1287        74   
1804                         -11               1              983       143   
1805                        -250              47            13423      1820   

      totale_casi  tamponi  casi_testati note_it note_en  
1801         9968   209161      151093.0     NaN     NaN  
1802         4358    70691       42125.0     NaN     NaN  
1803         1427    57822       40651.0     NaN     NaN  
1804         1175    12663        9862.0     NaN     NaN  
1805        18997   523800      280629.0     NaN     NaN

In [5]:
df.shape

(1806, 20)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1806 entries, 0 to 1805
Data columns (total 20 columns):
data                          1806 non-null object
stato                         1806 non-null object
codice_regione                1806 non-null int64
denominazione_regione         1806 non-null object
lat                           1806 non-null float64
long                          1806 non-null float64
ricoverati_con_sintomi        1806 non-null int64
terapia_intensiva             1806 non-null int64
totale_ospedalizzati          1806 non-null int64
isolamento_domiciliare        1806 non-null int64
totale_positivi               1806 non-null int64
variazione_totale_positivi    1806 non-null int64
nuovi_positivi                1806 non-null int64
dimessi_guariti               1806 non-null int64
deceduti                      1806 non-null int64
totale_casi                   1806 non-null int64
tamponi                       1806 non-null int64
casi_testati                  651 no

In [9]:
df.dtypes

data                           object
stato                          object
codice_regione                  int64
denominazione_regione          object
lat                           float64
long                          float64
ricoverati_con_sintomi          int64
terapia_intensiva               int64
totale_ospedalizzati            int64
isolamento_domiciliare          int64
totale_positivi                 int64
variazione_totale_positivi      int64
nuovi_positivi                  int64
dimessi_guariti                 int64
deceduti                        int64
totale_casi                     int64
tamponi                         int64
casi_testati                  float64
note_it                        object
note_en                        object
dtype: object

### Summary of all numerical fields in the dataset

In [10]:
df.describe(include = [np.number])

codice_regione          lat         long  ricoverati_con_sintomi  \
count     1806.000000  1806.000000  1806.000000             1806.000000   
mean        11.857143    43.046293    12.225955              788.468439   
std          6.275536     2.489470     2.659684             1794.347460   
min          1.000000    38.115697     7.320149                0.000000   
25%          7.000000    41.125596    11.121231               45.000000   
50%         12.000000    43.616760    12.388247              169.500000   
75%         17.000000    45.434905    13.768136              637.750000   
max         22.000000    46.499335    16.867367            12077.000000   

       terapia_intensiva  totale_ospedalizzati  isolamento_domiciliare  \
count        1806.000000           1806.000000              1806.00000   
mean           95.264120            883.732558              2198.04928   
std           190.715639           1979.157649              4276.43984   
min             0.000000              0.000000                 0.00000   
25%             6.000000             52.000000               110.50000   
50%            26.000000            204.000000               655.00000   
75%            98.000000            728.500000              2224.75000   
max          1381.000000          13328.000000             30382.00000   

       totale_positivi  variazione_totale_positivi  nuovi_positivi  \
count      1806.000000                 1806.000000     1806.000000   
mean       3081.781838                   35.940199      125.521041   
std        5970.062684                  244.050871      273.833470   
min           0.000000                -5339.000000      -18.000000   
25%         182.250000                  -11.000000        6.000000   
50%         878.500000                    5.000000       33.000000   
75%        2976.750000                   58.000000      111.000000   
max       37307.000000                 1950.000000     3251.000000   

       dimessi_guariti      deceduti   totale_casi        tamponi  \
count      1806.000000   1806.000000   1806.000000    1806.000000   
mean       1875.352159    741.658915   5698.792913   50145.484496   
std        4914.539316   2180.444611  12541.847494   86437.576859   
min           0.000000      0.000000      0.000000       0.000000   
25%           5.000000      9.250000    284.000000    2298.500000   
50%         215.500000    116.000000   1400.500000   15971.500000   
75%        1291.000000    403.750000   4440.250000   55520.000000   
max       42593.000000  15597.000000  85481.000000  596355.000000   

        casi_testati  
count     651.000000  
mean    70136.855607  
std     69824.977393  
min      3482.000000  
25%     23411.000000  
50%     41580.000000  
75%     99056.000000  
max    353579.000000

### Summary of all categorical fields in the dataset

In [11]:
df.describe(include = ['O'])

data stato denominazione_regione     note_it  \
count                  1806  1806                  1806          31   
unique                   86     1                    21          31   
top     2020-03-24T17:00:00   ITA               Liguria  nd-IT-0003   
freq                     21  1806                    86           1   

           note_en  
count           31  
unique          31  
top     dc-EN-0004  
freq             1

**FREQUENCY BREAKDOWN**

In [14]:
df['denominazione_regione'].value_counts()

Liguria                  86
P.A. Trento              86
Molise                   86
Friuli Venezia Giulia    86
Sicilia                  86
Emilia-Romagna           86
Lazio                    86
Umbria                   86
Toscana                  86
Abruzzo                  86
Valle d'Aosta            86
Basilicata               86
Lombardia                86
Sardegna                 86
Puglia                   86
P.A. Bolzano             86
Calabria                 86
Marche                   86
Veneto                   86
Campania                 86
Piemonte                 86
Name: denominazione_regione, dtype: int64

**PERCENTAGE BREAKDOWN**

In [15]:
df['denominazione_regione'].value_counts(1)

Liguria                  0.047619
P.A. Trento              0.047619
Molise                   0.047619
Friuli Venezia Giulia    0.047619
Sicilia                  0.047619
Emilia-Romagna           0.047619
Lazio                    0.047619
Umbria                   0.047619
Toscana                  0.047619
Abruzzo                  0.047619
Valle d'Aosta            0.047619
Basilicata               0.047619
Lombardia                0.047619
Sardegna                 0.047619
Puglia                   0.047619
P.A. Bolzano             0.047619
Calabria                 0.047619
Marche                   0.047619
Veneto                   0.047619
Campania                 0.047619
Piemonte                 0.047619
Name: denominazione_regione, dtype: float64

**COUNT OF NULL VALUES**

In [17]:
df['casi_testati'].isnull().sum()

1155

**COUNT OF NON-NULL VALUES**

In [19]:
df['casi_testati'].notnull().sum()

651

**LOOP THROUGH EACH COLUMN AND CHECK FOR NULLS**

In [16]:
for i in range(len(df.columns)):
    print(df.columns[i] + ": " + str(df[df.columns[i]].isna().sum()))

data: 0
stato: 0
codice_regione: 0
denominazione_regione: 0
lat: 0
long: 0
ricoverati_con_sintomi: 0
terapia_intensiva: 0
totale_ospedalizzati: 0
isolamento_domiciliare: 0
totale_positivi: 0
variazione_totale_positivi: 0
nuovi_positivi: 0
dimessi_guariti: 0
deceduti: 0
totale_casi: 0
tamponi: 0
casi_testati: 1155
note_it: 1775
note_en: 1775


**GET THE UNIQUE VALUES IN THE COLUMN**

In [20]:
df['casi_testati'].unique()

array([    nan,  22424.,   6528.,  14783.,  22234.,  34994.,  88776.,
        27544.,  22702.,  21103., 183757.,  27099.,   3482.,  71644.,
        41580.,  13760.,  49772.,  84620.,  16685.,  16790.,   3802.,
       161231.,  22552.,   6868.,  15089.,  22847.,  36153.,  90894.,
        28777.,  23067.,  21979., 173333.,  28006.,   3683.,  73192.,
        43119.,  14160.,  51373.,  85946.,  17347.,  17099.,   3910.,
       163757.,  23901.,   7470.,  15405.,  23914.,  37505.,  93367.,
        31352.,  24046.,  22670.,  29090.,   4015.,  76406.,  44760.,
        14526.,  55093.,  87717.,  17705.,  17873.,   3969., 167129.,
        24317.,   8040.,  15736.,  24878.,  38679.,  96824.,  32871.,
        25244.,  23756., 184323.,  30543.,   4252.,  81176.,  46925.,
        15354.,  58732.,  91747.,  17672.,  18679.,   4011., 171735.,
        24751.,   8511.,  16442.,  26187.,  99714.,  34057.,  26298.,
        25045., 190451.,  31673.,   4478.,  84648.,  49403.,  16094.,
        62150.,  944

**SELECT ONE COLUMNS**

In [21]:
df['casi_testati']

0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29           NaN
30           NaN
31           NaN
32           NaN
33           NaN
34           NaN
35           NaN
36           NaN
37           NaN
38           NaN
39           NaN
40           NaN
41           NaN
42           NaN
43           NaN
44           NaN
45           NaN
46           NaN
47           NaN
48           NaN
49           NaN
50           NaN
51           NaN
52           NaN
53           NaN
54           NaN
55           NaN
56           NaN
57           NaN
58           N

**SELECT MULTIPLE COLUMNS**

In [22]:
df[['data', 'totale_casi', 'casi_testati']]

data  totale_casi  casi_testati
0     2020-02-24T18:00:00            0           NaN
1     2020-02-24T18:00:00            0           NaN
2     2020-02-24T18:00:00            0           NaN
3     2020-02-24T18:00:00            0           NaN
4     2020-02-24T18:00:00            0           NaN
5     2020-02-24T18:00:00           18           NaN
6     2020-02-24T18:00:00            0           NaN
7     2020-02-24T18:00:00            3           NaN
8     2020-02-24T18:00:00            0           NaN
9     2020-02-24T18:00:00          172           NaN
10    2020-02-24T18:00:00            0           NaN
11    2020-02-24T18:00:00            0           NaN
12    2020-02-24T18:00:00            3           NaN
13    2020-02-24T18:00:00            0           NaN
14    2020-02-24T18:00:00            0           NaN
15    2020-02-24T18:00:00            0           NaN
16    2020-02-24T18:00:00            0           NaN
17    2020-02-24T18:00:00            0           NaN
18    2020-02-24T18:00:00            0           NaN
19    2020-02-24T18:00:00            0           NaN
20    2020-02-24T18:00:00           33           NaN
21    2020-02-25T18:00:00            0           NaN
22    2020-02-25T18:00:00            0           NaN
23    2020-02-25T18:00:00            1           NaN
24    2020-02-25T18:00:00            0           NaN
25    2020-02-25T18:00:00            0           NaN
26    2020-02-25T18:00:00           26           NaN
27    2020-02-25T18:00:00            0           NaN
28    2020-02-25T18:00:00            3           NaN
29    2020-02-25T18:00:00            1           NaN
30    2020-02-25T18:00:00          240           NaN
31    2020-02-25T18:00:00            0           NaN
32    2020-02-25T18:00:00            0           NaN
33    2020-02-25T18:00:00            3           NaN
34    2020-02-25T18:00:00            0           NaN
35    2020-02-25T18:00:00            0           NaN
36    2020-02-25T18:00:00            3           NaN
37    2020-02-25T18:00:00            2           NaN
38    2020-02-25T18:00:00            0           NaN
39    2020-02-25T18:00:00            0           NaN
40    2020-02-25T18:00:00            0           NaN
41    2020-02-25T18:00:00           43           NaN
42    2020-02-26T18:00:00            0           NaN
43    2020-02-26T18:00:00            0           NaN
44    2020-02-26T18:00:00            1           NaN
45    2020-02-26T18:00:00            0           NaN
46    2020-02-26T18:00:00            0           NaN
47    2020-02-26T18:00:00           47           NaN
48    2020-02-26T18:00:00            0           NaN
49    2020-02-26T18:00:00            3           NaN
50    2020-02-26T18:00:00           11           NaN
51    2020-02-26T18:00:00          258           NaN
52    2020-02-26T18:00:00            1           NaN
53    2020-02-26T18:00:00            0           NaN
54    2020-02-26T18:00:00            3           NaN
55    2020-02-26T18:00:00            0           NaN
56    2020-02-26T18:00:00            0           NaN
57    2020-02-26T18:00:00            3           NaN
58    2020-02-26T18:00:00            2           NaN
59    2020-02-26T18:00:00            0           NaN
60    2020-02-26T18:00:00            0           NaN
61    2020-02-26T18:00:00            0           NaN
62    2020-02-26T18:00:00           71           NaN
63    2020-02-27T18:00:00            1           NaN
64    2020-02-27T18:00:00            0           NaN
65    2020-02-27T18:00:00            1           NaN
66    2020-02-27T18:00:00            0           NaN
67    2020-02-27T18:00:00            3           NaN
68    2020-02-27T18:00:00           97           NaN
69    2020-02-27T18:00:00            0           NaN
70    2020-02-27T18:00:00            3           NaN
71    2020-02-27T18:00:00           19           NaN
72    2020-02-27T18:00:00          403           NaN
73    2020-02-27T18:00:00            3           NaN
74    2020-02-27T18:00:00            0        

**SElECT COLUMN NAMES**

In [23]:
df.columns

Index(['data', 'stato', 'codice_regione', 'denominazione_regione', 'lat',
       'long', 'ricoverati_con_sintomi', 'terapia_intensiva',
       'totale_ospedalizzati', 'isolamento_domiciliare', 'totale_positivi',
       'variazione_totale_positivi', 'nuovi_positivi', 'dimessi_guariti',
       'deceduti', 'totale_casi', 'tamponi', 'casi_testati', 'note_it',
       'note_en'],
      dtype='object')

**SELECT SUBSET OF DATA**

In [25]:
df.loc[1500:1600,['casi_testati']]

casi_testati
1500      255292.0
1501       44045.0
1502        7252.0
1503      126685.0
1504       67238.0
1505       25631.0
1506       82079.0
1507      118265.0
1508       25137.0
1509       27822.0
1510        6342.0
1511      227579.0
1512       31502.0
1513       15619.0
1514       20872.0
1515       39780.0
1516       49478.0
1517      138871.0
1518       50698.0
1519      125897.0
1520       37177.0
1521      262964.0
1522       45026.0
1523        7604.0
1524      131269.0
1525       68760.0
1526       26598.0
1527       83908.0
1528      121066.0
1529       26161.0
1530       28712.0
1531        6461.0
1532      231469.0
1533       32186.0
1534       15780.0
1535       21284.0
1536       40806.0
1537       50463.0
1538      141468.0
1539       51123.0
1540      130351.0
1541       38071.0
1542      262964.0
1543       46258.0
1544        7912.0
1545      134567.0
1546       51638.0
1547       27540.0
1548       85674.0
1549      124295.0
1550       28486.0
1551       29708.0
1552        6702.0
1553      236281.0
1554       32619.0
1555       16285.0
1556       21572.0
1557       41902.0
1558       51402.0
1559      144009.0
1560       52784.0
1561      133674.0
1562       39145.0
1563      277106.0
1564       47092.0
1565        8177.0
1566      138830.0
1567       53194.0
1568       28519.0
1569       88497.0
1570      126752.0
1571       29188.0
1572       30704.0
1573        6999.0
1574      240535.0
1575       33013.0
1576       16941.0
1577       21969.0
1578       42993.0
1579       52593.0
1580      146642.0
1581       55319.0
1582      137428.0
1583       39600.0
1584      282817.0
1585       47827.0
1586        8375.0
1587      141515.0
1588       54181.0
1589       29503.0
1590       90885.0
1591      129382.0
1592       30354.0
1593       31679.0
1594        7130.0
1595      244930.0
1596       33876.0
1597       17424.0
1598       22265.0
1599       44284.0
1600       53475.0

**SELECT ALL ROWS AND SPECIFIC COLUMN**

In [26]:
df.loc[:,['casi_testati']]

casi_testati
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
5              NaN
6              NaN
7              NaN
8              NaN
9              NaN
10             NaN
11             NaN
12             NaN
13             NaN
14             NaN
15             NaN
16             NaN
17             NaN
18             NaN
19             NaN
20             NaN
21             NaN
22             NaN
23             NaN
24             NaN
25             NaN
26             NaN
27             NaN
28             NaN
29             NaN
30             NaN
31             NaN
32             NaN
33             NaN
34             NaN
35             NaN
36             NaN
37             NaN
38             NaN
39             NaN
40             NaN
41             NaN
42             NaN
43             NaN
44             NaN
45             NaN
46             NaN
47             NaN
48             NaN
49             NaN
50             NaN
51             NaN
52             NaN
53             NaN
54             NaN
55             NaN
56             NaN
57             NaN
58             NaN
59             NaN
60             NaN
61             NaN
62             NaN
63             NaN
64             NaN
65             NaN
66             NaN
67             NaN
68             NaN
69             NaN
70             NaN
71             NaN
72             NaN
73             NaN
74             NaN
75             NaN
76             NaN
77             NaN
78             NaN
79             NaN
80             NaN
81             NaN
82             NaN
83             NaN
84             NaN
85             NaN
86             NaN
87             NaN
88             NaN
89             NaN
90             NaN
91             NaN
92             NaN
93             NaN
94             NaN
95             NaN
96             NaN
97             NaN
98             NaN
99             NaN
100            NaN
101            NaN
102            NaN
103            NaN
104            NaN
105            NaN
106            NaN
107            NaN
108            NaN
109            NaN
110            NaN
111            NaN
112            NaN
113            NaN
114            NaN
115            NaN
116            NaN
117            NaN
118            NaN
119            NaN
120            NaN
121            NaN
122            NaN
123            NaN
124            NaN
125            NaN
126            NaN
127            NaN
128            NaN
129            NaN
130            NaN
131            NaN
132            NaN
133            NaN
134            NaN
135            NaN
136            NaN
137            NaN
138            NaN
139            NaN
140            NaN
141            NaN
142            NaN
143            NaN
144            NaN
145            NaN
146            NaN
147            NaN
148            NaN
149            NaN
150            NaN
151            NaN
152            NaN
153            NaN
154            NaN
155            NaN
156            NaN
157            NaN
158            NaN
159            NaN
160            NaN
161            NaN
162            NaN
163            NaN
164            NaN
165            NaN
166            NaN
167            NaN
168            NaN
169            NaN
170            NaN
171            NaN
172            NaN
173            NaN
174            NaN
175            NaN
176            NaN
177            NaN
178            NaN
179            NaN
180            NaN
181            NaN
182            NaN
183            NaN
184            NaN
185            NaN
186            NaN
187            NaN
188            NaN
189            NaN
190            NaN
191            NaN
192            NaN
193            NaN
194            NaN
195            NaN
196            NaN
197            NaN
198            NaN
199            NaN
200            NaN
201            NaN
202            NaN
203            NaN
204            NaN
205            NaN
206            NaN
207            NaN
208            NaN
209            N

**SELECT COLUMN AT POSITION 2**

In [27]:
df.iloc[:,2]

0       13
1       17
2       21
3       18
4       15
5        8
6        6
7       12
8        7
9        3
10      11
11      14
12       1
13      16
14      20
15      19
16       9
17      22
18      10
19       2
20       5
21      13
22      17
23      21
24      18
25      15
26       8
27       6
28      12
29       7
30       3
31      11
32      14
33       1
34      16
35      20
36      19
37       9
38      22
39      10
40       2
41       5
42      13
43      17
44      21
45      18
46      15
47       8
48       6
49      12
50       7
51       3
52      11
53      14
54       1
55      16
56      20
57      19
58       9
59      22
60      10
61       2
62       5
63      13
64      17
65      21
66      18
67      15
68       8
69       6
70      12
71       7
72       3
73      11
74      14
75       1
76      16
77      20
78      19
79       9
80      22
81      10
82       2
83       5
84      13
85      17
86      21
87      18
88      15
89       8
90       6

**SELECT ONE ROW AT POSITION 3**

In [28]:
df.iloc[3,:]

data                          2020-02-24T18:00:00
stato                                         ITA
codice_regione                                 18
denominazione_regione                    Calabria
lat                                        38.906
long                                      16.5944
ricoverati_con_sintomi                          0
terapia_intensiva                               0
totale_ospedalizzati                            0
isolamento_domiciliare                          0
totale_positivi                                 0
variazione_totale_positivi                      0
nuovi_positivi                                  0
dimessi_guariti                                 0
deceduti                                        0
totale_casi                                     0
tamponi                                         1
casi_testati                                  NaN
note_it                                       NaN
note_en                                       NaN


**MASK FOR STRING COLUMNS** - Select all rows with region as Lazio

In [29]:
mask = df['denominazione_regione'] == "Lazio"
df[mask]

data stato  codice_regione denominazione_regione  \
7     2020-02-24T18:00:00   ITA              12                 Lazio   
28    2020-02-25T18:00:00   ITA              12                 Lazio   
49    2020-02-26T18:00:00   ITA              12                 Lazio   
70    2020-02-27T18:00:00   ITA              12                 Lazio   
91    2020-02-28T18:00:00   ITA              12                 Lazio   
112   2020-02-29T17:00:00   ITA              12                 Lazio   
133   2020-03-01T17:00:00   ITA              12                 Lazio   
154   2020-03-02T18:00:00   ITA              12                 Lazio   
175   2020-03-03T18:00:00   ITA              12                 Lazio   
196   2020-03-04T17:00:00   ITA              12                 Lazio   
217   2020-03-05T17:00:00   ITA              12                 Lazio   
238   2020-03-06T17:00:00   ITA              12                 Lazio   
259   2020-03-07T18:00:00   ITA              12                 Lazio   
280   2020-03-08T18:00:00   ITA              12                 Lazio   
301   2020-03-09T18:00:00   ITA              12                 Lazio   
322   2020-03-10T18:00:00   ITA              12                 Lazio   
343   2020-03-11T17:00:00   ITA              12                 Lazio   
364   2020-03-12T17:00:00   ITA              12                 Lazio   
385   2020-03-13T17:00:00   ITA              12                 Lazio   
406   2020-03-14T17:00:00   ITA              12                 Lazio   
427   2020-03-15T17:00:00   ITA              12                 Lazio   
448   2020-03-16T17:00:00   ITA              12                 Lazio   
469   2020-03-17T17:00:00   ITA              12                 Lazio   
490   2020-03-18T17:00:00   ITA              12                 Lazio   
511   2020-03-19T17:00:00   ITA              12                 Lazio   
532   2020-03-20T17:00:00   ITA              12                 Lazio   
553   2020-03-21T17:00:00   ITA              12                 Lazio   
574   2020-03-22T17:00:00   ITA              12                 Lazio   
595   2020-03-23T17:00:00   ITA              12                 Lazio   
616   2020-03-24T17:00:00   ITA              12                 Lazio   
637   2020-03-25T17:00:00   ITA              12                 Lazio   
658   2020-03-26T17:00:00   ITA              12                 Lazio   
679   2020-03-27T17:00:00   ITA              12                 Lazio   
700   2020-03-28T17:00:00   ITA              12                 Lazio   
721   2020-03-29T17:00:00   ITA              12                 Lazio   
742   2020-03-30T17:00:00   ITA              12                 Lazio   
763   2020-03-31T17:00:00   ITA              12                 Lazio   
784   2020-04-01T17:00:00   ITA              12                 Lazio   
805   2020-04-02T17:00:00   ITA              12                 Lazio   
826   2020-04-03T17:00:00   ITA              12                 Lazio   
847   2020-04-04T17:00:00   ITA              12                 Lazio   
868   2020-04-05T17:00:00   ITA              12                 Lazio   
889   2020-04-06T17:00:00   ITA              12                 Lazio   
910   2020-04-07T17:00:00   ITA              12                 Lazio   
931   2020-04-08T17:00:00   ITA              12                 Lazio   
952   2020-04-09T17:00:00   ITA              12                 Lazio   
973   2020-04-10T17:00:00   ITA              12                 Lazio   
994   2020-04-11T17:00:00   ITA              12                 Lazio   
1015  2020-04-12T17:00:00   ITA              12                 Lazio   
1036  2020-04-13T17:00:00   ITA              12                 Lazio   
1057  2020-04-14T17:00:00   ITA              12                 Lazio   
1078  2020-04-15T17:00:00   ITA              12                 Lazio   
1099  2020-04-16T17:00:00   ITA              12                 Lazio   
1120  2020-04-17T17:00:00   ITA              12                 Lazio   
1141  

**MASK FOR NUMERIC COLUMN**

In [34]:
mask2 = df['nuovi_positivi'] > 500
new_df = df[mask2]
new_df['denominazione_regione'].value_counts()

Lombardia         64
Piemonte          30
Emilia-Romagna    19
Veneto             6
Name: denominazione_regione, dtype: int64

**MASK FOR ITMES IN LIST**

In [35]:
# Get all the data for Lazio
mask3 = df['denominazione_regione'].isin(['Lazio'])
df[mask3]

data stato  codice_regione denominazione_regione  \
7     2020-02-24T18:00:00   ITA              12                 Lazio   
28    2020-02-25T18:00:00   ITA              12                 Lazio   
49    2020-02-26T18:00:00   ITA              12                 Lazio   
70    2020-02-27T18:00:00   ITA              12                 Lazio   
91    2020-02-28T18:00:00   ITA              12                 Lazio   
112   2020-02-29T17:00:00   ITA              12                 Lazio   
133   2020-03-01T17:00:00   ITA              12                 Lazio   
154   2020-03-02T18:00:00   ITA              12                 Lazio   
175   2020-03-03T18:00:00   ITA              12                 Lazio   
196   2020-03-04T17:00:00   ITA              12                 Lazio   
217   2020-03-05T17:00:00   ITA              12                 Lazio   
238   2020-03-06T17:00:00   ITA              12                 Lazio   
259   2020-03-07T18:00:00   ITA              12                 Lazio   
280   2020-03-08T18:00:00   ITA              12                 Lazio   
301   2020-03-09T18:00:00   ITA              12                 Lazio   
322   2020-03-10T18:00:00   ITA              12                 Lazio   
343   2020-03-11T17:00:00   ITA              12                 Lazio   
364   2020-03-12T17:00:00   ITA              12                 Lazio   
385   2020-03-13T17:00:00   ITA              12                 Lazio   
406   2020-03-14T17:00:00   ITA              12                 Lazio   
427   2020-03-15T17:00:00   ITA              12                 Lazio   
448   2020-03-16T17:00:00   ITA              12                 Lazio   
469   2020-03-17T17:00:00   ITA              12                 Lazio   
490   2020-03-18T17:00:00   ITA              12                 Lazio   
511   2020-03-19T17:00:00   ITA              12                 Lazio   
532   2020-03-20T17:00:00   ITA              12                 Lazio   
553   2020-03-21T17:00:00   ITA              12                 Lazio   
574   2020-03-22T17:00:00   ITA              12                 Lazio   
595   2020-03-23T17:00:00   ITA              12                 Lazio   
616   2020-03-24T17:00:00   ITA              12                 Lazio   
637   2020-03-25T17:00:00   ITA              12                 Lazio   
658   2020-03-26T17:00:00   ITA              12                 Lazio   
679   2020-03-27T17:00:00   ITA              12                 Lazio   
700   2020-03-28T17:00:00   ITA              12                 Lazio   
721   2020-03-29T17:00:00   ITA              12                 Lazio   
742   2020-03-30T17:00:00   ITA              12                 Lazio   
763   2020-03-31T17:00:00   ITA              12                 Lazio   
784   2020-04-01T17:00:00   ITA              12                 Lazio   
805   2020-04-02T17:00:00   ITA              12                 Lazio   
826   2020-04-03T17:00:00   ITA              12                 Lazio   
847   2020-04-04T17:00:00   ITA              12                 Lazio   
868   2020-04-05T17:00:00   ITA              12                 Lazio   
889   2020-04-06T17:00:00   ITA              12                 Lazio   
910   2020-04-07T17:00:00   ITA              12                 Lazio   
931   2020-04-08T17:00:00   ITA              12                 Lazio   
952   2020-04-09T17:00:00   ITA              12                 Lazio   
973   2020-04-10T17:00:00   ITA              12                 Lazio   
994   2020-04-11T17:00:00   ITA              12                 Lazio   
1015  2020-04-12T17:00:00   ITA              12                 Lazio   
1036  2020-04-13T17:00:00   ITA              12                 Lazio   
1057  2020-04-14T17:00:00   ITA              12                 Lazio   
1078  2020-04-15T17:00:00   ITA              12                 Lazio   
1099  2020-04-16T17:00:00   ITA              12                 Lazio   
1120  2020-04-17T17:00:00   ITA              12                 Lazio   
1141  

**MASK FOR ITMES NOT IN LIST**

In [37]:
mask3 = df['denominazione_regione'].isin(['Lombardia'])
df[~mask3] #tilda character allows you suxtract the opposite.

data stato  codice_regione  denominazione_regione  \
0     2020-02-24T18:00:00   ITA              13                Abruzzo   
1     2020-02-24T18:00:00   ITA              17             Basilicata   
2     2020-02-24T18:00:00   ITA              21           P.A. Bolzano   
3     2020-02-24T18:00:00   ITA              18               Calabria   
4     2020-02-24T18:00:00   ITA              15               Campania   
5     2020-02-24T18:00:00   ITA               8         Emilia-Romagna   
6     2020-02-24T18:00:00   ITA               6  Friuli Venezia Giulia   
7     2020-02-24T18:00:00   ITA              12                  Lazio   
8     2020-02-24T18:00:00   ITA               7                Liguria   
10    2020-02-24T18:00:00   ITA              11                 Marche   
11    2020-02-24T18:00:00   ITA              14                 Molise   
12    2020-02-24T18:00:00   ITA               1               Piemonte   
13    2020-02-24T18:00:00   ITA              16                 Puglia   
14    2020-02-24T18:00:00   ITA              20               Sardegna   
15    2020-02-24T18:00:00   ITA              19                Sicilia   
16    2020-02-24T18:00:00   ITA               9                Toscana   
17    2020-02-24T18:00:00   ITA              22            P.A. Trento   
18    2020-02-24T18:00:00   ITA              10                 Umbria   
19    2020-02-24T18:00:00   ITA               2          Valle d'Aosta   
20    2020-02-24T18:00:00   ITA               5                 Veneto   
21    2020-02-25T18:00:00   ITA              13                Abruzzo   
22    2020-02-25T18:00:00   ITA              17             Basilicata   
23    2020-02-25T18:00:00   ITA              21           P.A. Bolzano   
24    2020-02-25T18:00:00   ITA              18               Calabria   
25    2020-02-25T18:00:00   ITA              15               Campania   
26    2020-02-25T18:00:00   ITA               8         Emilia-Romagna   
27    2020-02-25T18:00:00   ITA               6  Friuli Venezia Giulia   
28    2020-02-25T18:00:00   ITA              12                  Lazio   
29    2020-02-25T18:00:00   ITA               7                Liguria   
31    2020-02-25T18:00:00   ITA              11                 Marche   
32    2020-02-25T18:00:00   ITA              14                 Molise   
33    2020-02-25T18:00:00   ITA               1               Piemonte   
34    2020-02-25T18:00:00   ITA              16                 Puglia   
35    2020-02-25T18:00:00   ITA              20               Sardegna   
36    2020-02-25T18:00:00   ITA              19                Sicilia   
37    2020-02-25T18:00:00   ITA               9                Toscana   
38    2020-02-25T18:00:00   ITA              22            P.A. Trento   
39    2020-02-25T18:00:00   ITA              10                 Umbria   
40    2020-02-25T18:00:00   ITA               2          Valle d'Aosta   
41    2020-02-25T18:00:00   ITA               5                 Veneto   
42    2020-02-26T18:00:00   ITA              13                Abruzzo   
43    2020-02-26T18:00:00   ITA              17             Basilicata   
44    2020-02-26T18:00:00   ITA              21           P.A. Bolzano   
45    2020-02-26T18:00:00   ITA              18               Calabria   
46    2020-02-26T18:00:00   ITA              15               Campania   
47    2020-02-26T18:00:00   ITA               8         Emilia-Romagna   
48    2020-02-26T18:00:00   ITA               6  Friuli Venezia Giulia   
49    2020-02-26T18:00:00   ITA              12                  Lazio   
50    2020-02-26T18:00:00   ITA               7                Liguria   
52    2020-02-26T18:00:00   ITA              11                 Marche   
53    2020-02-26T18:00:00   ITA              14                 Molise   
54    2020-02-26T18:00:00   ITA               1               Piemonte   
55    2020-02-26T18:00:00   ITA              16                 Puglia   
56    2020-02-26T18:00:00

**SELECT ALL COLUMSN THAT ARE NUMERIC DATA TYPES**

In [38]:
df.select_dtypes(include=[np.number])

codice_regione        lat       long  ricoverati_con_sintomi  \
0                 13  42.351222  13.398438                       0   
1                 17  40.639471  15.805148                       0   
2                 21  46.499335  11.356624                       0   
3                 18  38.905976  16.594402                       0   
4                 15  40.839566  14.250850                       0   
5                  8  44.494367  11.341721                      10   
6                  6  45.649435  13.768136                       0   
7                 12  41.892770  12.483667                       1   
8                  7  44.411493   8.932699                       0   
9                  3  45.466794   9.190347                      76   
10                11  43.616760  13.518875                       0   
11                14  41.557748  14.659161                       0   
12                 1  45.073274   7.680687                       2   
13                16  41.125596  16.867367                       0   
14                20  39.215312   9.110616                       0   
15                19  38.115697  13.362357                       0   
16                 9  43.769231  11.255889                       0   
17                22  46.068935  11.121231                       0   
18                10  43.106758  12.388247                       0   
19                 2  45.737503   7.320149                       0   
20                 5  45.434905  12.338452                      12   
21                13  42.351222  13.398438                       0   
22                17  40.639471  15.805148                       0   
23                21  46.499335  11.356624                       1   
24                18  38.905976  16.594402                       0   
25                15  40.839566  14.250850                       0   
26                 8  44.494367  11.341721                      15   
27                 6  45.649435  13.768136                       0   
28                12  41.892770  12.483667                       1   
29                 7  44.411493   8.932699                       1   
30                 3  45.466794   9.190347                      79   
31                11  43.616760  13.518875                       0   
32                14  41.557748  14.659161                       0   
33                 1  45.073274   7.680687                       2   
34                16  41.125596  16.867367                       0   
35                20  39.215312   9.110616                       0   
36                19  38.115697  13.362357                       1   
37                 9  43.769231  11.255889                       2   
38                22  46.068935  11.121231                       0   
39                10  43.106758  12.388247                       0   
40                 2  45.737503   7.320149                       0   
41                 5  45.434905  12.338452                      12   
42                13  42.351222  13.398438                       0   
43                17  40.639471  15.805148                       0   
44                21  46.499335  11.356624                       1   
45                18  38.905976  16.594402                       0   
46                15  40.839566  14.250850                       0   
47                 8  44.494367  11.341721                      20   
48                 6  45.649435  13.768136                       0   
49                12  41.892770  12.483667                       0   
50                 7  44.411493   8.932699                       6   
51                 3  45.466794   9.190347                      79   
52                11  43.616760  13.518875                       1   
53                14  41.557748  14.659161                       0   
54                 1  45.073274   7.680687                       2   
55                16  41.125596  16.867367                       0   
56              

**SELECT ALL COLUMSN THAT ARE CATEGORICAL DATA TYPES**

In [39]:
df.select_dtypes(include=['O'])

data stato  denominazione_regione     note_it     note_en
0     2020-02-24T18:00:00   ITA                Abruzzo         NaN         NaN
1     2020-02-24T18:00:00   ITA             Basilicata         NaN         NaN
2     2020-02-24T18:00:00   ITA           P.A. Bolzano         NaN         NaN
3     2020-02-24T18:00:00   ITA               Calabria         NaN         NaN
4     2020-02-24T18:00:00   ITA               Campania         NaN         NaN
5     2020-02-24T18:00:00   ITA         Emilia-Romagna         NaN         NaN
6     2020-02-24T18:00:00   ITA  Friuli Venezia Giulia         NaN         NaN
7     2020-02-24T18:00:00   ITA                  Lazio         NaN         NaN
8     2020-02-24T18:00:00   ITA                Liguria         NaN         NaN
9     2020-02-24T18:00:00   ITA              Lombardia         NaN         NaN
10    2020-02-24T18:00:00   ITA                 Marche         NaN         NaN
11    2020-02-24T18:00:00   ITA                 Molise         NaN         NaN
12    2020-02-24T18:00:00   ITA               Piemonte         NaN         NaN
13    2020-02-24T18:00:00   ITA                 Puglia         NaN         NaN
14    2020-02-24T18:00:00   ITA               Sardegna         NaN         NaN
15    2020-02-24T18:00:00   ITA                Sicilia         NaN         NaN
16    2020-02-24T18:00:00   ITA                Toscana         NaN         NaN
17    2020-02-24T18:00:00   ITA            P.A. Trento         NaN         NaN
18    2020-02-24T18:00:00   ITA                 Umbria         NaN         NaN
19    2020-02-24T18:00:00   ITA          Valle d'Aosta         NaN         NaN
20    2020-02-24T18:00:00   ITA                 Veneto         NaN         NaN
21    2020-02-25T18:00:00   ITA                Abruzzo         NaN         NaN
22    2020-02-25T18:00:00   ITA             Basilicata         NaN         NaN
23    2020-02-25T18:00:00   ITA           P.A. Bolzano         NaN         NaN
24    2020-02-25T18:00:00   ITA               Calabria         NaN         NaN
25    2020-02-25T18:00:00   ITA               Campania         NaN         NaN
26    2020-02-25T18:00:00   ITA         Emilia-Romagna         NaN         NaN
27    2020-02-25T18:00:00   ITA  Friuli Venezia Giulia         NaN         NaN
28    2020-02-25T18:00:00   ITA                  Lazio         NaN         NaN
29    2020-02-25T18:00:00   ITA                Liguria         NaN         NaN
30    2020-02-25T18:00:00   ITA              Lombardia         NaN         NaN
31    2020-02-25T18:00:00   ITA                 Marche         NaN         NaN
32    2020-02-25T18:00:00   ITA                 Molise         NaN         NaN
33    2020-02-25T18:00:00   ITA               Piemonte         NaN         NaN
34    2020-02-25T18:00:00   ITA                 Puglia         NaN         NaN
35    2020-02-25T18:00:00   ITA               Sardegna         NaN         NaN
36    2020-02-25T18:00:00   ITA                Sicilia         NaN         NaN
37    2020-02-25T18:00:00   ITA                Toscana         NaN         NaN
38    2020-02-25T18:00:00   ITA            P.A. Trento         NaN         NaN
39    2020-02-25T18:00:00   ITA                 Umbria         NaN         NaN
40    2020-02-25T18:00:00   ITA          Valle d'Aosta         NaN         NaN
41    2020-02-25T18:00:00   ITA                 Veneto         NaN         NaN
42    2020-02-26T18:00:00   ITA                Abruzzo         NaN         NaN
43    2020-02-26T18:00:00   ITA             Basilicata         NaN         NaN
44    2020-02-26T18:00:00   ITA           P.A. Bolzano         NaN         NaN
45    2020-02-26T18:00:00   ITA               Calabria         NaN         NaN
46    2020-02-26T18:00:00   ITA               Campania         NaN         NaN
47    2020-02-26T18:00:00   ITA         Emilia-Romagna         NaN         NaN
48    2020-02-26T18:00:00   ITA  Friuli Venezia Giulia         NaN         NaN
49    2020-02-26T18:00:00   ITA                  Lazio         NaN     

<h1>CLEANING DATA</h1>

In [52]:
# Load dataset again for practice
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")

**REPLACE WORD "ITA" WITH "ITALIA"**

In [44]:
df.replace({'ITA': 'ITALIA'}, inplace=True)
df.head()

data   stato  codice_regione denominazione_regione  \
0  2020-02-24T18:00:00  ITALIA              13               Abruzzo   
1  2020-02-24T18:00:00  ITALIA              17            Basilicata   
2  2020-02-24T18:00:00  ITALIA              21          P.A. Bolzano   
3  2020-02-24T18:00:00  ITALIA              18              Calabria   
4  2020-02-24T18:00:00  ITALIA              15              Campania   

         lat       long  ricoverati_con_sintomi  terapia_intensiva  \
0  42.351222  13.398438                       0                  0   
1  40.639471  15.805148                       0                  0   
2  46.499335  11.356624                       0                  0   
3  38.905976  16.594402                       0                  0   
4  40.839566  14.250850                       0                  0   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                     0                       0                0   
1                     0                       0                0   
2                     0                       0                0   
3                     0                       0                0   
4                     0                       0                0   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0               0                0         0   
1                           0               0                0         0   
2                           0               0                0         0   
3                           0               0                0         0   
4                           0               0                0         0   

   totale_casi  tamponi  casi_testati note_it note_en  
0            0        5           NaN     NaN     NaN  
1            0        0           NaN     NaN     NaN  
2            0        1           NaN     NaN     NaN  
3            0        1           NaN     NaN     NaN  
4            0       10           NaN     NaN     NaN

**FILL NAN values in dataset with 0**

In [46]:
df.fillna(0, inplace=True)
df.head()

data   stato  codice_regione denominazione_regione  \
0  2020-02-24T18:00:00  ITALIA              13               Abruzzo   
1  2020-02-24T18:00:00  ITALIA              17            Basilicata   
2  2020-02-24T18:00:00  ITALIA              21          P.A. Bolzano   
3  2020-02-24T18:00:00  ITALIA              18              Calabria   
4  2020-02-24T18:00:00  ITALIA              15              Campania   

         lat       long  ricoverati_con_sintomi  terapia_intensiva  \
0  42.351222  13.398438                       0                  0   
1  40.639471  15.805148                       0                  0   
2  46.499335  11.356624                       0                  0   
3  38.905976  16.594402                       0                  0   
4  40.839566  14.250850                       0                  0   

   totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
0                     0                       0                0   
1                     0                       0                0   
2                     0                       0                0   
3                     0                       0                0   
4                     0                       0                0   

   variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
0                           0               0                0         0   
1                           0               0                0         0   
2                           0               0                0         0   
3                           0               0                0         0   
4                           0               0                0         0   

   totale_casi  tamponi  casi_testati note_it note_en  
0            0        5           0.0       0       0  
1            0        0           0.0       0       0  
2            0        1           0.0       0       0  
3            0        1           0.0       0       0  
4            0       10           0.0       0       0

**Drop nulls**

In [48]:
# Not suggested to drop straight away as Null rows may contains valuable insights for data analysis
df.dropna(inplace=True)
df.head() 

data stato  codice_regione  denominazione_regione  \
1185  2020-04-20T17:00:00   ITA               3              Lombardia   
1206  2020-04-21T17:00:00   ITA               3              Lombardia   
1243  2020-04-23T17:00:00   ITA              15               Campania   
1246  2020-04-23T17:00:00   ITA              12                  Lazio   
1266  2020-04-24T17:00:00   ITA               6  Friuli Venezia Giulia   

            lat       long  ricoverati_con_sintomi  terapia_intensiva  \
1185  45.466794   9.190347                   10138                901   
1206  45.466794   9.190347                    9805                851   
1243  40.839566  14.250850                     539                 47   
1246  41.892770  12.483667                    1385                186   
1266  45.649435  13.768136                     136                 16   

      totale_ospedalizzati  isolamento_domiciliare  totale_positivi  \
1185                 11039                   23548            34587   
1206                 10656                   23322            33978   
1243                   586                    2392             2978   
1246                  1571                    2915             4486   
1266                   152                    1168             1320   

      variazione_totale_positivi  nuovi_positivi  dimessi_guariti  deceduti  \
1185                          90             735            20008     12376   
1206                        -609             960            21374     12579   
1243                         -20              53              928       332   
1246                          23              79             1193       375   
1266                         185              24             1304       258   

      totale_casi  tamponi  casi_testati     note_it     note_en  
1185        66971   270486      173333.0  dc-IT-0006  dc-EN-0006  
1206        67931   277197      173333.0  pd-IT-0012  pd-EN-0012  
1243         4238    58324       38679.0  pd-IT-0014  pd-EN-0014  
1246         6054   111073       26298.0  pd-IT-0016  pd-EN-0016  
1266         2882    55502       35547.0  dc-IT-0008  dc-EN-0008

**Let's bring back the dataset again so we can work with the two null records**

In [49]:
df = pd.read_csv("https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-regioni/dpc-covid19-ita-regioni.csv")
df['casi_testati'].head(20)

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
Name: casi_testati, dtype: float64

**Impute null values with mean**

In [50]:
df['casi_testati'].fillna(df['casi_testati'].mean(), inplace=True)
df['casi_testati'].head(20)

0     70136.855607
1     70136.855607
2     70136.855607
3     70136.855607
4     70136.855607
5     70136.855607
6     70136.855607
7     70136.855607
8     70136.855607
9     70136.855607
10    70136.855607
11    70136.855607
12    70136.855607
13    70136.855607
14    70136.855607
15    70136.855607
16    70136.855607
17    70136.855607
18    70136.855607
19    70136.855607
Name: casi_testati, dtype: float64

**Drop columns 'note_it' and 'note_en' **

In [53]:
df.drop(columns = ['note_it', 'note_en'], inplace = True)
df.head() #Notice that the 'note_it' and column is gone

data stato  codice_regione denominazione_regione        lat  \
0  2020-02-24T18:00:00   ITA              13               Abruzzo  42.351222   
1  2020-02-24T18:00:00   ITA              17            Basilicata  40.639471   
2  2020-02-24T18:00:00   ITA              21          P.A. Bolzano  46.499335   
3  2020-02-24T18:00:00   ITA              18              Calabria  38.905976   
4  2020-02-24T18:00:00   ITA              15              Campania  40.839566   

        long  ricoverati_con_sintomi  terapia_intensiva  totale_ospedalizzati  \
0  13.398438                       0                  0                     0   
1  15.805148                       0                  0                     0   
2  11.356624                       0                  0                     0   
3  16.594402                       0                  0                     0   
4  14.250850                       0                  0                     0   

   isolamento_domiciliare  totale_positivi  variazione_totale_positivi  \
0                       0                0                           0   
1                       0                0                           0   
2                       0                0                           0   
3                       0                0                           0   
4                       0                0                           0   

   nuovi_positivi  dimessi_guariti  deceduti  totale_casi  tamponi  \
0               0                0         0            0        5   
1               0                0         0            0        0   
2               0                0         0            0        1   
3               0                0         0            0        1   
4               0                0         0            0       10   

   casi_testati  
0           NaN  
1           NaN  
2           NaN  
3           NaN  
4           NaN

**Drop row index 2**

In [54]:
df.drop(2, axis=0, inplace=True)
df

data stato  codice_regione  denominazione_regione  \
0     2020-02-24T18:00:00   ITA              13                Abruzzo   
1     2020-02-24T18:00:00   ITA              17             Basilicata   
3     2020-02-24T18:00:00   ITA              18               Calabria   
4     2020-02-24T18:00:00   ITA              15               Campania   
5     2020-02-24T18:00:00   ITA               8         Emilia-Romagna   
6     2020-02-24T18:00:00   ITA               6  Friuli Venezia Giulia   
7     2020-02-24T18:00:00   ITA              12                  Lazio   
8     2020-02-24T18:00:00   ITA               7                Liguria   
9     2020-02-24T18:00:00   ITA               3              Lombardia   
10    2020-02-24T18:00:00   ITA              11                 Marche   
11    2020-02-24T18:00:00   ITA              14                 Molise   
12    2020-02-24T18:00:00   ITA               1               Piemonte   
13    2020-02-24T18:00:00   ITA              16                 Puglia   
14    2020-02-24T18:00:00   ITA              20               Sardegna   
15    2020-02-24T18:00:00   ITA              19                Sicilia   
16    2020-02-24T18:00:00   ITA               9                Toscana   
17    2020-02-24T18:00:00   ITA              22            P.A. Trento   
18    2020-02-24T18:00:00   ITA              10                 Umbria   
19    2020-02-24T18:00:00   ITA               2          Valle d'Aosta   
20    2020-02-24T18:00:00   ITA               5                 Veneto   
21    2020-02-25T18:00:00   ITA              13                Abruzzo   
22    2020-02-25T18:00:00   ITA              17             Basilicata   
23    2020-02-25T18:00:00   ITA              21           P.A. Bolzano   
24    2020-02-25T18:00:00   ITA              18               Calabria   
25    2020-02-25T18:00:00   ITA              15               Campania   
26    2020-02-25T18:00:00   ITA               8         Emilia-Romagna   
27    2020-02-25T18:00:00   ITA               6  Friuli Venezia Giulia   
28    2020-02-25T18:00:00   ITA              12                  Lazio   
29    2020-02-25T18:00:00   ITA               7                Liguria   
30    2020-02-25T18:00:00   ITA               3              Lombardia   
31    2020-02-25T18:00:00   ITA              11                 Marche   
32    2020-02-25T18:00:00   ITA              14                 Molise   
33    2020-02-25T18:00:00   ITA               1               Piemonte   
34    2020-02-25T18:00:00   ITA              16                 Puglia   
35    2020-02-25T18:00:00   ITA              20               Sardegna   
36    2020-02-25T18:00:00   ITA              19                Sicilia   
37    2020-02-25T18:00:00   ITA               9                Toscana   
38    2020-02-25T18:00:00   ITA              22            P.A. Trento   
39    2020-02-25T18:00:00   ITA              10                 Umbria   
40    2020-02-25T18:00:00   ITA               2          Valle d'Aosta   
41    2020-02-25T18:00:00   ITA               5                 Veneto   
42    2020-02-26T18:00:00   ITA              13                Abruzzo   
43    2020-02-26T18:00:00   ITA              17             Basilicata   
44    2020-02-26T18:00:00   ITA              21           P.A. Bolzano   
45    2020-02-26T18:00:00   ITA              18               Calabria   
46    2020-02-26T18:00:00   ITA              15               Campania   
47    2020-02-26T18:00:00   ITA               8         Emilia-Romagna   
48    2020-02-26T18:00:00   ITA               6  Friuli Venezia Giulia   
49    2020-02-26T18:00:00   ITA              12                  Lazio   
50    2020-02-26T18:00:00   ITA               7                Liguria   
51    2020-02-26T18:00:00   ITA               3              Lombardia   
52    2020-02-26T18:00:00   ITA              11                 Marche   
53    2020-02-26T18:00:00   ITA              14                 Molise   
54    2020-02-26T18:00:00

In [57]:

new_column_names_dict = {
    'data': 'date',
    'stato': 'state',
    'codice_regione': 'region code',
    'denominazione_regione': 'region name',
    'lat': 'latitude',
    'long': 'longitude',
    'ricoverati_con_sintomi': 'hospitalized_with_symptoms',
    'terapia_intensiva': 'intensive care',
    'totale_ospedalizzati': 'total hospitalized',
    'isolamento_domiciliare': 'home isolation',
    'totale_positivi': 'total positives', 
    'variazione_totale_positivi': 'total positive change',
    'nuovi_positivi': 'new positives',
    'dimessi_guariti': 'discharged healed',
    'deceduti': 'deceased',
    'totale_casi': 'total cases',
    'tamponi': 'tampons',
    'casi_testati': 'total tests',
    'note_it': 'notes in italian',
    'note_en': 'notes in english'
}


df.rename(columns = new_column_names_dict, inplace = True)
df.head()

date state  region code     region name   latitude  \
0  2020-02-24T18:00:00   ITA           13         Abruzzo  42.351222   
1  2020-02-24T18:00:00   ITA           17      Basilicata  40.639471   
3  2020-02-24T18:00:00   ITA           18        Calabria  38.905976   
4  2020-02-24T18:00:00   ITA           15        Campania  40.839566   
5  2020-02-24T18:00:00   ITA            8  Emilia-Romagna  44.494367   

   longitude  hospitalized_with_symptoms  intensive care  total hospitalized  \
0  13.398438                           0               0                   0   
1  15.805148                           0               0                   0   
3  16.594402                           0               0                   0   
4  14.250850                           0               0                   0   
5  11.341721                          10               2                  12   

   home isolation  total positives  total positive change  new positives  \
0               0                0                      0              0   
1               0                0                      0              0   
3               0                0                      0              0   
4               0                0                      0              0   
5               6               18                      0             18   

   discharged healed  deceased  total cases  tampons  total tests  
0                  0         0            0        5          NaN  
1                  0         0            0        0          NaN  
3                  0         0            0        1          NaN  
4                  0         0            0       10          NaN  
5                  0         0           18      148          NaN

In [58]:
df['tampons'].apply(np.sqrt)

0         2.236068
1         0.000000
3         1.000000
4         3.162278
5        12.165525
6         7.615773
7        11.135529
8         1.000000
9        38.249183
10        4.000000
11        0.000000
12       11.874342
13        0.000000
14        1.000000
15        2.236068
16       11.832160
17        1.732051
18        0.000000
19        2.645751
20       46.904158
21        2.236068
22        0.000000
23        1.000000
24        1.414214
25        3.162278
26       19.773720
27        9.433981
28       11.135529
29        6.244998
30       60.827625
31        4.582576
32        0.000000
33       11.874342
34        0.000000
35        1.000000
36        2.236068
37       17.204651
38        1.732051
39        2.828427
40        2.645751
41       61.481705
42        3.605551
43        0.000000
44        1.000000
45        1.732051
46        3.162278
47       24.020824
48       10.677078
49       11.135529
50        8.124038
51       56.639209
52        5.291503
53        0.

<h1>DATA AGGREGATION</h1>

**Mean of records in "age" column, grouped by column "embark_town"**

In [59]:
df.groupby(by=['region name'])['new positives'].mean()

region name
Abruzzo                   37.174419
Basilicata                 4.569767
Calabria                  13.406977
Campania                  54.732558
Emilia-Romagna           317.604651
Friuli Venezia Giulia     37.244186
Lazio                     87.255814
Liguria                  107.639535
Lombardia                993.895349
Marche                    77.616279
Molise                     4.906977
P.A. Bolzano              30.435294
P.A. Trento               50.674419
Piemonte                 345.662791
Puglia                    51.116279
Sardegna                  15.744186
Sicilia                   39.569767
Toscana                  115.906977
Umbria                    16.593023
Valle d'Aosta             13.662791
Veneto                   220.883721
Name: new positives, dtype: float64

**Sum of records in "new positives" column, grouped by column "region name"**

In [60]:
df.groupby(by=['region name'])['new positives'].sum()

region name
Abruzzo                   3197
Basilicata                 393
Calabria                  1153
Campania                  4707
Emilia-Romagna           27314
Friuli Venezia Giulia     3203
Lazio                     7504
Liguria                   9257
Lombardia                85475
Marche                    6675
Molise                     422
P.A. Bolzano              2587
P.A. Trento               4358
Piemonte                 29727
Puglia                    4396
Sardegna                  1354
Sicilia                   3403
Toscana                   9968
Umbria                    1427
Valle d'Aosta             1175
Veneto                   18996
Name: new positives, dtype: int64

**Count of records in "new positives" column, grouped by column "region name"**

In [61]:
df.groupby(by=['region name'])['new positives'].count()

region name
Abruzzo                  86
Basilicata               86
Calabria                 86
Campania                 86
Emilia-Romagna           86
Friuli Venezia Giulia    86
Lazio                    86
Liguria                  86
Lombardia                86
Marche                   86
Molise                   86
P.A. Bolzano             85
P.A. Trento              86
Piemonte                 86
Puglia                   86
Sardegna                 86
Sicilia                  86
Toscana                  86
Umbria                   86
Valle d'Aosta            86
Veneto                   86
Name: new positives, dtype: int64

**so we have data for 86 days from the dataset**

**Mean of "age" column, grouped by two columns: "embark_town" and "class_name"**

In [64]:
#df.groupby(by=['date', 'region name'])['new positives'].mean()

df.groupby(by=['region name', 'date'])['new positives'].mean()

region name    date               
Abruzzo        2020-02-24T18:00:00      0
               2020-02-25T18:00:00      0
               2020-02-26T18:00:00      0
               2020-02-27T18:00:00      1
               2020-02-28T18:00:00      0
               2020-02-29T17:00:00      1
               2020-03-01T17:00:00      3
               2020-03-02T18:00:00      0
               2020-03-03T18:00:00      1
               2020-03-04T17:00:00      1
               2020-03-05T17:00:00      1
               2020-03-06T17:00:00      1
               2020-03-07T18:00:00      2
               2020-03-08T18:00:00      6
               2020-03-09T18:00:00     13
               2020-03-10T18:00:00      8
               2020-03-11T17:00:00      0
               2020-03-12T17:00:00     46
               2020-03-13T17:00:00      5
               2020-03-14T17:00:00     23
               2020-03-15T17:00:00     25
               2020-03-16T17:00:00     39
               2020-03-17T17:00:00     53

<h1>COMBINING MULTIPLE DATFRAMES</h1>

In [0]:
dfs1 = pd.read_csv("https://raw.githubusercontent.com/julia-git/Soils_DataSet/master/Soils.csv")
dfs2 = pd.read_csv("https://raw.githubusercontent.com/julia-git/Soils_DataSet/master/Soils2.csv")

**Concatenate data by column**

In [0]:
pd.concat([dfs1, dfs2], axis=1)

Group     Contour  Depth  Gp  Block    pH      N  Dens    P     Ca     Mg  \
0       1         Top   0-10  T0      1  5.40  0.188  0.92  215  16.35   7.65   
1       1         Top   0-10  T0      2   NaN  0.165  1.04  208  12.25   5.15   
2       1        Topk   0-10  T0      3  5.14  0.260  0.95  300  13.02   5.68   
3       1         Top   0-10  T0      4  5.14  0.169  1.10  248  11.92   7.88   
4       2         Top  10-30  T1      1  5.14  0.164  1.12  174  14.17   8.12   
5       2         Top  10-30  T1      2  5.10  0.094  1.22  129   8.55   6.92   
6       2         Top  10-30  T1      3  4.70  0.100  1.52  117   8.74   8.16   
7       2         Top  10-30  T1      4  4.46  0.112  1.47  170   9.49   9.16   
8       3         Top  30-60  T3      1  4.37  0.112  1.07  121   8.85  10.35   
9       3         Top  30-60  T3      2  4.39  0.058  1.54  115   4.73   6.91   
10      3         Top  30-60  T3      3  4.17  0.078  1.26  112   6.29   7.95   
11      3         Top  30-60  T3      4  3.89  0.070  1.42  117   6.61   9.76   
12      4         Top  60-90  T6      1  3.88  0.077  1.25  127   6.41  10.96   
13      4         Top  60-90  T6      2  4.07  0.046  1.54   91   3.82   6.61   
14      4         Top  60-90  T6      3  3.88  0.055  1.53   91   4.98   8.00   
15      4         Top  60-90  T6      4  3.74  0.053  1.40   79   5.86  10.14   
16      5       Slope   0-10  S0      1  5.11  0.247  0.94  261  13.25   7.55   
17      5       Slope   0-10  S0      2  5.46  0.298  0.96  300  12.30   7.50   
18      5       Slope   0-10  S0      3   NaN  0.145  1.10  242   9.66   6.76   
19      5       Slope   0-10  S0      4  5.85  0.186  1.20  229  13.78   7.12   
20      6       Slope  10-30  S1      1  4.57  0.102  1.37  156   8.58   9.92   
21      6       Slope  10-30  S1      2  5.11  0.097  1.30  139   8.58   8.69   
22      6       Slope  10-30  S1      3  4.78  0.122  1.30  214   8.22   7.75   
23      6       Slope  10-30  S1      4  6.67  0.083  1.42  132  12.68   9.56   
24      7       Slope  30-60  S3      1  3.96  0.059  1.53   98   4.80  10.00   
25      7       Slope  30-60  S3      2  4.00  0.050  1.50  115   5.06   8.91   
26      7       Slope  30-60  S3      3  4.12  0.086  1.55  148   6.16   7.58   
27      7       Slope  30-60  S3      4  4.99  0.048  1.46   97   7.49   9.38   
28      8       Slope  60-90  S6      1  3.80  0.049  1.48  108   3.82   8.80   
29      8       Slope  60-90  S6      2  3.96  0.036  1.28  103   4.78   7.29   
30      8       Slope  60-90  S6      3  3.93  0.048  1.42  109   4.93   7.47   
31      8       Slope  60-90  S6      4  4.02  0.039  1.51  100   5.66   8.84   
32      9  Depression   0-10  D0      1  5.24  0.194  1.00  445  12.27   6.27   
33      9  Depression   0-10  D0      2  5.20  0.256  0.78  380  11.39   7.55   
34      9  Depression   0-10  D0      3  5.30  0.136  1.00  259   9.96   8.08   
35      9  Depression   0-10  D0      4  5.67  0.127  1.13  248   9.12   7.04   
36     10  Depression  10-30  D1      1  4.46  0.087  1.24  276   7.24   9.40   
37     10  Depression  10-30  D1      2  4.91  0.092  1.47  158   7.37  10.57   
38     10  Depression  10-30  D1      3  4.79  0.047  1.46  121   6.99   9.91   
39     10  Depression  10-30  D1      4  5.36  0.095  1.26  195   8.59   8.66   
40     11  Depression  30-60  D3      1  3.94  0.054  1.60  148   4.85   9.62   
41     11  Depression  30-60  D3      2  4.52  0.051  1.53  115   6.34   9.78   
42     11  Depression  30-60  D3      3  4.35  0.032  1.55   82   5.99   9.73   
43     11  Depression  30-60  D3      4  4.64  0.065  1.46  152   4.43  10.54   
44     12  Depression  60-90  D6      1  3.82  0.038  1.40  105   4.65   9.85   
45     12  Depression  60-90  D6      2  4.24  0.035  1.47  100   4.56   8.95   
46     12  Depression  60-90  D6      3  4.22  0.030  1.56   97   5.29   8.37   
47     12  Depression  60-90  D6      4  4.41  0.058  1.58  130   4.58   9.46   

       K     Na  Conduc  Group    

**Concatenate data by row**

In [0]:
pd.concat([dfs1, dfs2], axis=0)

Group     Contour  Depth  Gp  Block     pH       N   Dens      P      Ca  \
0       1         Top   0-10  T0      1  5.400  0.1880  0.920  215.0  16.350   
1       1         Top   0-10  T0      2    NaN  0.1650  1.040  208.0  12.250   
2       1        Topk   0-10  T0      3  5.140  0.2600  0.950  300.0  13.020   
3       1         Top   0-10  T0      4  5.140  0.1690  1.100  248.0  11.920   
4       2         Top  10-30  T1      1  5.140  0.1640  1.120  174.0  14.170   
5       2         Top  10-30  T1      2  5.100  0.0940  1.220  129.0   8.550   
6       2         Top  10-30  T1      3  4.700  0.1000  1.520  117.0   8.740   
7       2         Top  10-30  T1      4  4.460  0.1120  1.470  170.0   9.490   
8       3         Top  30-60  T3      1  4.370  0.1120  1.070  121.0   8.850   
9       3         Top  30-60  T3      2  4.390  0.0580  1.540  115.0   4.730   
10      3         Top  30-60  T3      3  4.170  0.0780  1.260  112.0   6.290   
11      3         Top  30-60  T3      4  3.890  0.0700  1.420  117.0   6.610   
12      4         Top  60-90  T6      1  3.880  0.0770  1.250  127.0   6.410   
13      4         Top  60-90  T6      2  4.070  0.0460  1.540   91.0   3.820   
14      4         Top  60-90  T6      3  3.880  0.0550  1.530   91.0   4.980   
15      4         Top  60-90  T6      4  3.740  0.0530  1.400   79.0   5.860   
16      5       Slope   0-10  S0      1  5.110  0.2470  0.940  261.0  13.250   
17      5       Slope   0-10  S0      2  5.460  0.2980  0.960  300.0  12.300   
18      5       Slope   0-10  S0      3    NaN  0.1450  1.100  242.0   9.660   
19      5       Slope   0-10  S0      4  5.850  0.1860  1.200  229.0  13.780   
20      6       Slope  10-30  S1      1  4.570  0.1020  1.370  156.0   8.580   
21      6       Slope  10-30  S1      2  5.110  0.0970  1.300  139.0   8.580   
22      6       Slope  10-30  S1      3  4.780  0.1220  1.300  214.0   8.220   
23      6       Slope  10-30  S1      4  6.670  0.0830  1.420  132.0  12.680   
24      7       Slope  30-60  S3      1  3.960  0.0590  1.530   98.0   4.800   
25      7       Slope  30-60  S3      2  4.000  0.0500  1.500  115.0   5.060   
26      7       Slope  30-60  S3      3  4.120  0.0860  1.550  148.0   6.160   
27      7       Slope  30-60  S3      4  4.990  0.0480  1.460   97.0   7.490   
28      8       Slope  60-90  S6      1  3.800  0.0490  1.480  108.0   3.820   
29      8       Slope  60-90  S6      2  3.960  0.0360  1.280  103.0   4.780   
30      8       Slope  60-90  S6      3  3.930  0.0480  1.420  109.0   4.930   
31      8       Slope  60-90  S6      4  4.020  0.0390  1.510  100.0   5.660   
32      9  Depression   0-10  D0      1  5.240  0.1940  1.000  445.0  12.270   
33      9  Depression   0-10  D0      2  5.200  0.2560  0.780  380.0  11.390   
34      9  Depression   0-10  D0      3  5.300  0.1360  1.000  259.0   9.960   
35      9  Depression   0-10  D0      4  5.670  0.1270  1.130  248.0   9.120   
36     10  Depression  10-30  D1      1  4.460  0.0870  1.240  276.0   7.240   
37     10  Depression  10-30  D1      2  4.910  0.0920  1.470  158.0   7.370   
38     10  Depression  10-30  D1      3  4.790  0.0470  1.460  121.0   6.990   
39     10  Depression  10-30  D1      4  5.360  0.0950  1.260  195.0   8.590   
40     11  Depression  30-60  D3      1  3.940  0.0540  1.600  148.0   4.850   
41     11  Depression  30-60  D3      2  4.520  0.0510  1.530  115.0   6.340   
42     11  Depression  30-60  D3      3  4.350  0.0320  1.550   82.0   5.990   
43     11  Depression  30-60  D3      4  4.640  0.0650  1.460  152.0   4.430   
44     12  Depression  60-90  D6      1  3.820  0.0380  1.400  105.0   4.650   
45     12  Depression  60-90  D6      2  4.240  0.0350  1.470  100.0   4.560   
46     12  Depression  60-90  D6      3  4.220  0.0300  1.560   97.0   5.290   
47     12  Depression  60-90  D6      4  4.410  0.0580  1.580  130.0   4.580   
0      13         Top   0-10  T0      1  6.080  0.3256  0.704  257.6  19.220   
1   

**Outer join on the two dataframes on the "Contour" columns**

In [0]:
pd.merge(dfs1, dfs2, left_on='Contour', right_on='Contour', how='outer')

Group_x     Contour Depth_x Gp_x  Block_x  pH_x    N_x  Dens_x  P_x  \
0          1         Top    0-10   T0        1  5.40  0.188    0.92  215   
1          1         Top    0-10   T0        1  5.40  0.188    0.92  215   
2          1         Top    0-10   T0        1  5.40  0.188    0.92  215   
3          1         Top    0-10   T0        1  5.40  0.188    0.92  215   
4          1         Top    0-10   T0        1  5.40  0.188    0.92  215   
..       ...         ...     ...  ...      ...   ...    ...     ...  ...   
733       12  Depression   60-90   D6        4  4.41  0.058    1.58  130   
734       12  Depression   60-90   D6        4  4.41  0.058    1.58  130   
735       12  Depression   60-90   D6        4  4.41  0.058    1.58  130   
736       12  Depression   60-90   D6        4  4.41  0.058    1.58  130   
737       12  Depression   60-90   D6        4  4.41  0.058    1.58  130   

      Ca_x  Mg_x   K_x  Na_x  Conduc_x  Group_y Depth_y Gp_y  Block_y   pH_y  \
0    16.35  7.65  0.72  1.14      1.09       13    0-10   T0        1  6.080   
1    16.35  7.65  0.72  1.14      1.09       13    0-10   T0        2  6.200   
2    16.35  7.65  0.72  1.14      1.09       13    0-10   T0        4  5.768   
3    16.35  7.65  0.72  1.14      1.09       14   10-30   T1        1  5.768   
4    16.35  7.65  0.72  1.14      1.09       14   10-30   T1        2  5.720   
..     ...   ...   ...   ...       ...      ...     ...  ...      ...    ...   
733   4.58  9.46  0.14  9.28     12.69       23   30-60   D3        4  5.168   
734   4.58  9.46  0.14  9.28     12.69       24   60-90   D6        1  4.184   
735   4.58  9.46  0.14  9.28     12.69       24   60-90   D6        2  4.688   
736   4.58  9.46  0.14  9.28     12.69       24   60-90   D6        3  4.664   
737   4.58  9.46  0.14  9.28     12.69       24   60-90   D6        4  4.892   

        N_y  Dens_y    P_y    Ca_y    Mg_y    K_y    Na_y  Conduc_y  
0    0.3256   0.704  257.6  19.220   8.780  0.144   0.968     0.908  
1    0.2980   0.848  249.2  14.300   5.780  0.142   0.728     1.220  
2    0.3028   0.920  297.2  13.904   9.056  0.218   0.812     1.568  
3    0.2968   0.944  208.4  16.604   9.344  0.140   2.204     1.820  
4    0.2128   1.064  154.4   9.860   7.904  0.162   2.804     3.416  
..      ...     ...    ...     ...     ...    ...     ...       ...  
733  0.1780   1.352  182.0   4.916  12.248  0.044   8.732    10.508  
734  0.1456   1.280  125.6   5.180  11.420  0.036  11.780    14.312  
735  0.1420   1.364  119.6   5.072  10.340  0.066  12.212    13.148  
736  0.1360   1.472  116.0   5.948   9.644  0.028   9.524    11.012  
737  0.1696   1.496  155.6   5.096  10.952  0.028  10.736    14.828  

[738 rows x 27 columns]

<h1>EXPORTING DATA</h1>

In [0]:
#Export data to csv, delimit by tab
dfs1.to_csv('myDataFrame.csv', sep='\t')

In [0]:
#Export data to excel
writer = pd.ExcelWriter('myDataFrame.xlsx') 
dfs1.to_excel(writer, 'DataFrame') 
writer.save()

In [5]:
# Other notes
import pandas as pd
import numpy as np


# Reading in CSV files. Use the read_csv command.
# More options: https://pandas.pydata.org/pandas-docs/stable/io.html
df = pd.read_csv('salaries.csv')

print(df)


# You can select columns with a bracket call:
print(df['Name'])


print(df['Salary'])


# Select multiple columns with a list of column names.
# Since you are passing in a list, you see two sets of []
print(df[['Name','Salary']])


# Similar to NumPy, you can create calls of min(), max(), mean(), etc...
# on a pandas dataframe.

print(df['Age'].mean())


# Just like Numpy, we can use conditional filtering to select rows that meet
# certain critera. Like choosing rows where the Age value is greater than 30

ser_of_bool = df['Age'] > 30
print(ser_of_bool)

# Use this filter of booleans to then select the rows

age_filter = df['Age'] > 30

# Pass it to the dataframe
print(df[age_filter])


# More commonly done all in one step:
df[df['Age'] > 30]


# There are lots of other commands you can do with pandas!
# But for now, we'll just talk about a few more, and then introduce the rest
# as we continue through the course :)

df['Age'].unique() # list of unique values for Age
df['Age'].nunique() # number of unqiue values
df.info() # General info about your dataframe
df.describe() # Statistics about your dataframe
df.columns # Grab a list of all columns
df.index # Create an index list
# You can convert a numpy matrix to a dataframe with:
mat = np.arange(50).reshape(5,10)

df = pd.DataFrame(data=mat)


mat = np.arange(0,10).reshape(5,2)

df = pd.DataFrame(data=mat, columns=['A', 'B'])

print(df)



     Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27
0      John
1     Sally
2    Alyssa
Name: Name, dtype: object
0     50000
1    120000
2     80000
Name: Salary, dtype: int64
     Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000
35.333333333333336
0     True
1     True
2    False
Name: Age, dtype: bool
    Name  Salary  Age
0   John   50000   34
1  Sally  120000   45
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Salary  3 non-null      int64 
 2   Age     3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes
   A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9


In [6]:
# Exercises
#######
# TASK 1: Import pandas and numpy
######
import numpy as np
import pandas as pd


#######
# TASK 2: Set Numpy's random number generator seed to 101
######

np.random.seed(101)

#######
# TASK 3: Create a NumPy Matrix of 100 rows by 5 columns consisting of
#         random integers from 1-100. (Keep in mind that the upper
#         limit may be exclusive.)
######
mat = np.random.randint(1,101,(100,5))
print(mat)


#######
# TASK 4: Now use pd.DataFrame() to read in this numpy array as a dataframe.
#         Simple pass in the numpy array into that function to get back a
#         dataframe. Pandas will auto label the columns to 0-4
######

df = pd.DataFrame(mat)
print(df)

#######
# TASK 5: Using your previously created DataFrame, use [df.columns = [...]]
#         (https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas)
#         to rename the pandas columns to be ['f1','f2','f3','f4','label'].
######

df.columns = ['f1','f2','f3','f4','label']

#######
# TASK 6: Alright, all the other tasks were hopefully straightforward.
#         This final task will allow you to quickly check to see if you are at
#         the right level with pandas! Do the following:
#         Create a dataframe with the columns ['A','B','C','D'] with each column
#         having 50 rows of random numbers for data. The random numbers should be
#         between 0 and 100. (Hint: Use numpy to create the numbers, then pass
#         it in to pd.DataFrame(), check out the data= and index= parameters
#         for that call.)
random_numbers = np.random.randint(0,100,200)
random_mat = random_numbers.reshape(50,4)
col_names = 'A B C D'.split()
df = pd.DataFrame(data = random_mat,columns=col_names)

[[ 96  12  82  71  64]
 [ 88  76  10  78  41]
 [  5  64  41  61  93]
 [ 65   6  13  94  41]
 [ 50  84   9  30  60]
 [ 35  45  73  20  11]
 [ 77  96  88   1  74]
 [  9  63  37  84 100]
 [ 29  64   8  11  53]
 [ 57  39  74  53  19]
 [ 72  16  45   1  13]
 [ 18  76  80  98  94]
 [ 25  37  64  20  36]
 [ 31  11  61  21  28]
 [  9  87  27  88  47]
 [ 48  55  87  10  46]
 [  3  19  59  93  12]
 [ 11  95  36  29   4]
 [ 84  85  48  15  70]
 [ 61  70  52   7  89]
 [ 72  69  24  36  80]
 [ 99  68  83  58  78]
 [ 47   4  47  30  87]
 [ 22  22  82  24  95]
 [ 72  21  28  76   6]
 [ 50  87  90  64  83]
 [ 78   4  57  15  50]
 [ 88  53  14  48  50]
 [ 25  21  65  53  61]
 [ 48  30  61  54  12]
 [ 41  92  46  98  25]
 [ 37  39  10  53  68]
 [ 44   2  80  69  69]
 [ 62  19  52  15  29]
 [ 18  88  47  53  17]
 [ 71  72  85  11  63]
 [ 97  58  24  87  86]
 [ 27  77  67  55  18]
 [ 66  58  90   3  81]
 [ 51  67  89  80  94]
 [  7  93  43  23  21]
 [ 26  98  55  72  73]
 [ 81  94  65  64  81]
 [ 39  46  